spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    show-sql: false
  flyway:
    baseline-on-migrate: false

logging:
  level:
    root: WARN
    dev.chol.globechat: INFO
